package com.berkekucuk.mmaapp.core.presentation.strings

import com.berkekucuk.mmaapp.core.presentation.AppLanguage
import com.berkekucuk.mmaapp.core.utils.AppError
import com.berkekucuk.mmaapp.domain.enums.ReportReason

data class AppStrings(
    val language: AppLanguage,
    val tabUpcoming: String,
    val tabCompleted: String,
    val toBeAnnounced: String,
    val tba: String,
    val liveEvent: String,
    val selectYear: String,
    val contentDescriptionFlag: String,
    val contentDescriptionInfo: String,
    val contentDescriptionWin: String,
    val contentDescriptionLoss: String,
    val eventDetailsFallback: String,
    val contentDescriptionBack: String,
    val tabMainCard: String,
    val tabPrelims: String,
    val emptyMainCardFights: String,
    val emptyPrelimFights: String,
    val tabFightDetails: String,
    val tabFightComparison: String,
    val fightDetailLabelName: String,
    val fightDetailLabelAge: String,
    val fightDetailLabelHometown: String,
    val fightDetailLabelHeight: String,
    val fightDetailLabelReach: String,
    val fightDetailLabelResult: String,
    val fightDetailLabelOdds: String,
    val fightDetailLabelRecord: String,
    val fightDetailLabelRoundsFormat: String,
    val fightDetailLabelMethod: String,
    val fightDetailLabelRoundSummary: String,
    val heightCm: (String) -> String,
    val radarLabelHeight: String,
    val radarLabelReach: String,
    val radarLabelOdds: String,
    val radarLabelWinRate: String,
    val radarLabelKoTkoRate: String,
    val radarLabelSubRate: String,
    val rankingsTitle: String,
    val tabMens: String,
    val tabWomens: String,
    val rankingsChampion: String,
    val rankingsVacant: String,
    val contentDescriptionCollapse: String,
    val contentDescriptionExpand: String,
    val rankingsChampionRankLabel: String,
    val tabOverview: String,
    val tabFights: String,
    val fighterDetailLabelRecord: String,
    val fighterDetailLabelWeightClass: String,
    val fighterDetailLabelHeight: String,
    val fighterDetailLabelReach: String,
    val fighterDetailLabelAge: String,
    val fighterDetailLabelDateOfBirth: String,
    val fighterDetailLabelBorn: String,
    val fighterDetailLabelFightingOutOf: String,
    val fighterDetailValueUnavailable: String,
    val fighterDetailAgeYears: (String, String) -> String,
    val fighterDetailRecordWins: String,
    val fighterDetailRecordLosses: String,
    val fighterDetailRecordDraws: String,
    val fighterDetailResultWin: String,
    val fighterDetailResultLoss: String,
    val fighterDetailResultDraw: String,
    val fighterDetailResultNoContest: String,
    val fighterDetailResultPending: String,
    val profileEdit: String,
    val profileSignOut: String,
    val profileTabOverview: String,
    val profileTabPredictions: String,
    val emptyPredictionList: String,
    val emptyInteractionList: String,
    val profileFavoriteFighters: String,
    val profileGoatFighters: String,
    val profileHatedFighters: String,
    val profileJoinedDate: (String) -> String,
    val profileEditTitle: String,
    val profileEditPersonalInfo: String,
    val profileEditEmail: String,
    val profileEditFullName: String,
    val profileEditUsernameLabel: String,
    val profileEditSaveChanges: String,
    val profileEditDeleteAccount: String,
    val profileEditDeleteAccountTitle: String,
    val profileEditDeleteAccountConfirm: String,
    val reportUserTitle: String,
    val reportUserSubmit: String,
    val reportReasonDisplayName: (ReportReason) -> String,
    val blockUserTitle: String,
    val blockUserConfirm: String,
    val fighterSearchPlaceholder: String,
    val fighterSearchEmpty: String,
    val userSearchPlaceholder: String,
    val userSearchEmpty: String,
    val retry: String,
    val dialogAccept: String,
    val dialogCancel: String,
    val fightReminderDialogTitle: String,
    val fightReminderDialogMessage: String,
    val fightReminderRemoveDialogTitle: String,
    val notificationPermissionSettingsTitle: String,
    val notificationPermissionSettingsMessage: String,
    val fullScreenIntentSettingsTitle: String,
    val fullScreenIntentSettingsMessage: String,
    val riskUnsure: String,
    val riskNormal: String,
    val riskConfident: String,
    val riskAllIn: String,
    val settingsTitle: String,
    val settingsSectionLanguage: String,
    val settingsSectionMeasurements: String,
    val settingsSectionOdds: String,
    val settingsSectionTheme: String,
    val settingsThemeLight: String,
    val settingsThemeDark: String,
    val settingsSectionBlockedUsers: String,
    val settingsSectionBlockedUsersSub: String,
    val settingsSectionSupport: String,
    val settingsSectionSupportSub: String,
    val unblockUser: String,
    val blockedUsersEmpty: String,
    val menuSignInPrompt: String,
    val menuTitle: String,
    val menuItemLeaderboard: String,
    val menuItemNotifications: String,
    val menuItemSettings: String,
    val menuSignInButton: String,
    val menuSignInTerms: String,
    val menuSignInPrivacyPolicy: String,
    val menuProfileSettings: String,
    val menuSignInWithGoogle: String,
    val menuSignInWithApple: String,
    val menuNotificationsEnabled: String,
    val menuNotificationsDisabled: String,
    val navEvents: String,
    val navRankings: String,
    val navMenu: String,
    val weightClassDisplayName: (String) -> String,
    val resultDisplayName: (String) -> String,
    val toUpperCase: (String) -> String,
    val predictionQuestionTitle: String,
    val predictionConfirmTitle: String,
    val predictionConfirmMessage: (String) -> String,
    val leaderboardInfoTitle: String,
    val leaderboardInfoClose: String,
    val tabOverall: String,
    val tabWeekly: String,
    val notificationChannelName: String,
    val notificationChannelDescription: String,
    val commonRemove: String,
    val commonCancel: String,
    val profileRemoveFighterConfirm: (String) -> String,
    val interactionLimitReachedTitle: String,
    val interactionLimitReachedText: String,
    val dialogOkay: String,
    val mapError: (AppError?) -> String?,
    val updateForceTitle: String,
    val updateForceMessage: String,
    val updateFlexibleTitle: String,
    val updateFlexibleMessage: String,
    val updateButton: String,
    val updateLaterButton: String,
    val alarmFightTime: String,
    val alarmDismiss: String,
    val notificationTypeTitle: String,
    val notificationTypeMessage: String,
    val notificationTypeRegular: String,
    val notificationTypeAlarm: String,
)